apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-trigger-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-trigger-role
  namespace: default
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "taskruns"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]  # Core API group
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-trigger-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: tekton-trigger-sa
roleRef:
  kind: Role
  name: tekton-trigger-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pipeline-trigger-binding
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.head_commit.id)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: git-event-listener
spec:
  serviceAccountName: tekton-trigger-sa
  triggers:
    - name: trigger-pipeline
      binding:
        ref: pipeline-trigger-binding
      template:
        ref: pipeline-template

